street/apps/main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.search, name='search'),
    path('stats/', views.StatsView, name = 'stats'),
    path('<int:street_id>/segment/<int:segment_id>/', views.segment_detail, name='segment_detail'),
    path('street_chronology/<int:street>', views.StreetChronologyView, name = 'street_chronology' ),
    path('search_ajax/', views.search_ajax, name = 'search_ajax'),
    path('<int:street_id>/', views.detail, name='detail'),
    path('document/new/', views.document_new, name='document_new'),
    path('street/new/', views.street_new, name='street_new'),
    path('<int:street_id>/street/rename/', views.street_rename, name='street_rename'),
    path('<int:street_id>/segment/new/', views.segment_new, name='segment_new'),
    path('operations/<int:doc_id>/', views.operations, name='operations'),
    path('<int:street_id>/segment/<int:segment_id>/change/geom/', views.segment_change_geom, name='segment_change_geom'),
    path('<int:street_id>/segment/<int:segment_id>/change/attributes/', views.segment_change_attributes, name='segment_change_attributes'),
    path('<int:street_id>/report/', views.export_street_segments, name='export'),
    path('<int:street_id>/import/', views.simple_upload, name='import'),
    path('signup/', views.signup, name='signup'),
]

street/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

street/apps/dictionaries/models.py
from django.db import models

class DictStreetOperations(models.Model):
    name = models.CharField('Назва операції',max_length = 100, null=True)
    description = models.CharField('Опис операції',max_length = 100, null=True)

    def __str__(self):
        return self.description

    class Meta:

        db_table = 'dit_dict_street_operations'
        verbose_name = 'Тип операції'
        verbose_name_plural = 'Словник типів операцій'



class DictStreetGeomType(models.Model):
    name = models.CharField('Тип геометрії',max_length = 100, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:

        db_table = 'dit_dict_street_geom_type'
        verbose_name = 'Тип геометрії'
        verbose_name_plural = 'Словник типів геометрій'


class DictStreetTopocode(models.Model):
    name = models.CharField('Топокод',max_length = 100, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:

        db_table = 'dit_dict_street_topocode'
        verbose_name = 'Топокод'
        verbose_name_plural = 'Словник топокодів'


class DictDistricts(models.Model):
    name = models.CharField('Назва району',max_length = 100, blank=True, null=True)
    # topocode = models.ForeignKey(DictStreetTopocode, models.DO_NOTHING, blank=True, null=True)
    # geom_type = models.ForeignKey(DictStreetGeomType, models.DO_NOTHING, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:

        db_table = 'dit_dict_districts'
        verbose_name = 'Район'
        verbose_name_plural = 'Словник районів'


class DictStreetTract(models.Model):
    name = models.CharField('Тип тракту',max_length = 100, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:

        db_table = 'dit_dict_street_tract'
        verbose_name = 'Тип тракту'
        verbose_name_plural = 'Словник типів тракту'


class DictStreetType(models.Model):
    name = models.CharField('Тип вулиці',max_length= 100, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:

        db_table = 'dit_dict_street_type'
        verbose_name = 'Тип Вулиці'
        verbose_name_plural = 'Словник типів вулиць'

class DictBalanceHolder(models.Model):
    name = models.TextField('Назва балансоутримувача', blank=True, null=True)
    class Meta:
        db_table = 'dit_dict_balance_holder'

street/apps/main/forms.py
from django.contrib.gis import forms

from .models import *

class DocumentsStreetForm(forms.ModelForm):

    class Meta:
        model = DocumentsStreet
        fields = ('name', 'document', 'date',)

class StreetForm(forms.ModelForm):

    class Meta:
        model = Street
        fields = ('name', 'type',)

class OperationStreetForm(forms.ModelForm):

    class Meta:
        model = OperationStreet
        fields = ('date',)

class SegmentForm(forms.ModelForm):
    geom = forms.MultiLineStringField(widget=
        forms.OSMWidget(attrs={
            'map_width': 800,
            'map_height': 500,
            'default_lat': 50.45466,
            'default_lon': 30.5238,
            'default_zoom': 10}))
    class Meta:
        model = Segment
        fields = ('district', 'geom')

class SegmentChangeGeomForm(forms.ModelForm):
    geom = forms.MultiLineStringField(widget=
        forms.OSMWidget(attrs={
            'default_zoom': 16,
            'map_width': 800,
            'map_height': 500,}))
    class Meta:
        model = Segment
        fields = ('geom',)
        

class ChangeSegmentAttributesForm(forms.ModelForm):
    class Meta:
        model = Segment
        fields = ('width', 'cover_type')


class OperationSegmentForm(forms.ModelForm):

    class Meta:
        model = OperationSegment
        fields = ('date',)

street/apps/dictionaries/views.py
from django.shortcuts import render

# Create your views here.

street/apps/main/views.py
import os
import copy
import xlwt
from django.views.decorators.cache import cache_page
from .models import *
from .forms import *
from django.shortcuts import render, redirect
from datetime import datetime, date
from django.db.models import Q, Count, Sum
from django.http import Http404, HttpResponseRedirect, JsonResponse, HttpResponse
from django.urls import reverse
from django.views.generic import DetailView, ListView
from dictionaries.models import *
from django.contrib.gis.db.models.functions import Length
from tablib import Dataset
from main.resources import *
from django.utils.encoding import escape_uri_path
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('main:search')
    else:
        form = UserCreationForm()
    return render(request, 'main/signup.html', {'form': form})


def simple_upload(request, street_id):
    if request.method == 'POST':
        person_resource = SegmentResource()
        dataset = Dataset()
        new_persons = request.FILES['myfile']

        imported_data = dataset.load(new_persons.read())
        result = person_resource.import_data(dataset, dry_run=True)  # Test the data import

        if not result.has_errors():
            person_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'main/import.html')

def export_street_segments(request, street_id):
    response = HttpResponse(content_type='application/ms-excel')
    street = Street.objects.get(id = street_id)
    filename = '{}:{}.xls'.format(street.type.name, street.name)
    response['Content-Disposition'] = "attachment; filename*=UTF-8''"+ escape_uri_path(filename)

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Segments')
    
    # Sheet header, first row
    row_num = 0
    ws.write(row_num, 0, street.type.name + ": " + street.name)

    row_num = 1

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['id', 'Район', 'Довжина', ]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    rows = Segment.objects.filter(street__id=street_id).annotate(leng = (Length('geom')))
    for row in rows:
        row_num += 1
        ws.write(row_num, 0, row.id, font_style)
        ws.write(row_num, 1, row.district.name, font_style)
        ws.write(row_num, 2, str(row.leng), font_style)

    wb.save(response)
    return response

@cache_page(60*60)
def StatsView(request):
    streets = Street.objects.all()
    s = Segment.objects.all().distinct('district', 'street')
    values = [[i.name, s.filter(district=i.id).count()] for i in DictDistricts.objects.all()]

    split_by=25
    min_len=0
    max_len=5000
    step = (max_len - min_len) / split_by
    q = Segment.objects.values('street').annotate(leng = Sum(Length('geom')))
    ret = [[
        "≤ " + str(int(min_len + step * (i + 1))),
        q.filter(leng__gte= min_len + step * i)
         .filter(leng__lt= min_len + step * (i + 1))
         .count()]
        for i in range(split_by)]
    street_count = Street.objects.count()
    segment_count = Segment.objects.count()
    return render(request, 'main/stats.html', {'values':values, 'len_stat':ret, 'street_count': street_count, 'segment_count': segment_count,})

def StreetChronologyView(request, street):
    if request.method == 'POST' and 'date' in request.POST:
        dat = request.POST['date']
        dat = datetime.strptime(dat, '%Y-%m-%d')
    else:
        dat = date.today()
    s = Street.objects.get(id = street)
    hash_street = s.AllChronologicSegments(dat)
    return render(request, 'main/street_chronology.html', {'street_id': street, 'date': dat, 'hash_street': hash_street})

def search(request):
    if request.method == 'POST' and 'date' in request.POST:
        dat = request.POST['date']
    else:
        dat = date.today()
    date_now = date.today()
    street_list = Street.ActualStreets(dat)
    street_count = street_list.count()
    district_list = DictDistricts.objects.all()
    street_type_list = DictStreetType.objects.all()
    return render(request, 'main/street_list.html', { 'street_list': street_list, 'street_count': street_count, 'district_list': district_list, 'street_type_list': street_type_list, 'date_now': str(date_now)})

def search_ajax(request):
    if request.is_ajax():
        searchDate = request.GET['searchDate']
        if not searchDate:
            searchDate = date.today()
        searchName = request.GET['searchName']
        street = Street.ActualStreets(searchDate)
        street = street.filter(Q(name__icontains=searchName) | Q(streetalternativename__name__icontains=searchName))

        district = int(request.GET['district'])
        type_street = int(request.GET['type'])

        if district > 0:
            street = street.filter(segmentstreet__segment__district = district)       

        if type_street > 0:
            street = street.filter(type__id = type_street)

        street = street.distinct().order_by('id')

        street_list = list(street.values_list('id', 'name', 'type__name'))
        count_of_segments = count_segments_for_streets(street_list, searchDate)
        # q = list(Segment.objects.values('street').annotate(leng = Sum(Length('geom'))).order_by('street').values_list('leng'))
        # q = [str(i[0]) for i in q]
        response = {'street_list': street_list, 'count_of_segments': count_of_segments}

        return JsonResponse(response, safe=False)
    else:
        raise Http404

def detail(request, street_id):
    if request.method == 'POST' and 'date' in request.POST:
        dat = request.POST['date']
        dat = datetime.strptime(dat, '%Y-%m-%d')
    else:
        dat = date.today()

    street = Street.objects.get(id = street_id)
    segment_list = street.SegmentsByDate(dat)
    xcoord, ycoord = street.Centroid()
    return render(request, 'main/detail.html', {'street': street, 'segment_list': segment_list, 'xcoord': xcoord, 'ycoord': ycoord, 'segment_count': segment_list.count(), 'date_now': str(date.today())})


def segment_detail(request, street_id, segment_id):
    segment = Segment.objects.get(id = segment_id)
    xcoord = segment.geom.centroid.x
    ycoord = segment.geom.centroid.y
    return render(request, 'main/segment_detail.html', {'segment': segment, 'street_id': street_id, 'xcoord': xcoord, 'ycoord': ycoord})

def segment_change_geom(request, street_id, segment_id):#move to models
    if not 'doc_id' in request.session:
        return redirect('main:document_new')
    else:
        street = Street.objects.get(id = street_id)
        doc_id = request.session['doc_id']
        document = DocumentsStreet.objects.get(id = doc_id)
        segment = Segment.objects.get(id = segment_id)
        if request.method == "POST":
            form = SegmentChangeGeomForm(request.POST, instance=segment)
            if form.is_valid():
                segment_new = copy.copy(segment)
                segment_new.id = None

                segment_new.geom = form.save(commit=False).geom
                segment_new.save()

                form_operation = OperationSegmentForm(request.POST)
                operation = form_operation.save(commit=False)
                operation.document = document
                operation.new = segment_new
                operation.old = segment
                operation.save()

                street.segments.add(segment_new)

                segment_street = SegmentStreet.objects.get(street = street.id, segment = segment.id)
                segment_street.date_end = operation.date
                segment_street.save()

                segment_street = SegmentStreet.objects.get(street = street.id, segment = segment_new.id)
                segment_street.date_start = operation.date
                segment_street.save()

                return redirect('main:segment_detail', street_id=street.id, segment_id=segment_new.id)
        else:
            form = SegmentChangeGeomForm(instance=segment)
            form_operation = OperationSegmentForm()
            return render(request, 'main/segment_change_geom.html', {'form': form, 'form_operation': form_operation, 'document': document, 'segment': segment})


def segment_change_attributes(request, street_id, segment_id):
    pass


def document_new(request):
    if request.method == "POST":
        form = DocumentsStreetForm(request.POST, request.FILES)
        if form.is_valid():
            document = form.save(commit=False)
            document.save()
            path_to_file = "street/media/" + str(document.document)
            outdir = os.path.dirname(path_to_file)
            path_to_converted_file = os.path.splitext(str(document.document))[0] + ".pdf"
            os.system("libreoffice --headless --convert-to pdf " + path_to_file + " --outdir " + outdir)
            document.path_pdf = path_to_converted_file
            document.save()
            request.session['doc_id'] = document.id
            return redirect('main:operations', doc_id=document.id)
    else:
        form = DocumentsStreetForm()
    return render(request, 'main/add_document.html', {'form': form})


def street_new(request):
    if not 'doc_id' in request.session:

street/templates/main/add_document.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/add_document.css' %}">

<div class="w3-content">
    <div class="w3-black w3-bar w3-center">
      <h2>Додати документ:</h2>
    </div>
    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="w3-button w3-black w3-right">Зберегти</button>
    </form>
</div>
{% endblock %}

street/templates/main/add_segment.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/add_document.css' %}">

<div class="w3-content">
    <div class="w3-black w3-bar w3-center">
      <h2>Додати сегмент до вулиці {{ street.name }}:</h2>
      <p>На основі документу:</p>
      <a target = "_blank" href = "/media/{{ document.path_pdf }}" class="w3-xlarge">{{ document.origin_name }} ({{ document.name }}) {{ document.date }}</a>
    </div>
    <form method="POST" class="post-form">{% csrf_token %}
      <head>
        {{ form.media }}
      </head>
        {{ form_operation.as_p }}
        {{ form.as_p }}
        <button type="submit" class="w3-button w3-black w3-right">Зберегти</button>
    </form>
</div>
{% endblock %}

street/templates/main/add_street.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/add_document.css' %}">

<div class="w3-content">
    <div class="w3-black w3-bar w3-center">
      <h2>Додати вулицю:</h2>
      <p>На основі документу:</p>
      <a target = "_blank" href = "/media/{{ document.path_pdf }}" class="w3-xlarge">{{ document.origin_name }} ({{ document.name }}) {{ document.date }}</a>
    </div>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form_operation.as_p }}
        {{ form.as_p }}
        <button type="submit" class="w3-button w3-black w3-right">Зберегти</button>
    </form>
</div>
{% endblock %}

street/templates/main/detail.html
{% extends 'base_sidebar.html' %}

{% block navbar-items %}
  {{ block.super }}
    <a id="top_bar_item" class="w3-bar-item w3-left w3-button w3-padding w3-hover-white" href="{% url 'main:street_chronology' street.id %}"><i class="fa fa-clock-o"></i>  Переглянути хронологію вулиці</a>
    <a id="top_bar_item" class="w3-bar-item w3-left w3-padding w3-white">{{street.type}}: {{ street.name }}</a>
    <button id="top_bar_item" class="w3-bar-item w3-button w3-hover-white" onclick="open_right();"><i class="fa fa-info-circle"></i></button>
{% endblock %}


{% block sidebar-content %}
  {{ block.super }} 
    <a id="sidebar_item" class="w3-bar-item w3-button w3-padding w3-hover-teal" href="{% url 'main:segment_new' street.id %}">
    <i class="fa fa-road" ></i>  Додати сегмент</a>
  <a id="sidebar_item" class="w3-bar-item w3-button w3-padding w3-hover-teal" 
    href="{% url 'main:street_rename' street.id %}">
    <i class="fa fa-edit"></i>  Додати вулицю</a>
{% endblock %}


{% block content %}

{% load static %}

{% load leaflet_tags %}
{% leaflet_css %}
{% leaflet_js %}
<link rel="stylesheet" href="{% static 'css/street_list.css' %}">
<div id="map-container" style="height: 100%">
  <div id="map" style="height: 100%;">{% leaflet_map "main" callback="map_init" %}</div>
</div>

<div id="right_sidebar" class="w3-white w3-container w3-padding" style="display:none; height:100%; position: fixed; top:40px; right:0px; z-index: 1000;">
  <a class="w3-button w3-teal w3-round-large" href="{% url 'main:export' street.id %}"><i class="fa fa-book"></i>  Сформувати звіт</a>
  <a class="w3-button w3-teal w3-round-large" href="{% url 'main:import' street.id %}"><i class="fa fa-upload"></i>  Імпорт сегментів</a>
  <!-- Кількість сегментів: {{ street.count_segments_by_date }} -->
  <form method="POST" class="post-form" action="{% url 'main:detail' street.id %}">{% csrf_token %}
    <label for="#date">Переглянути вулицю на дату:</label>
    <input required id="date" name="date" type="date">
    <button type="submit" class="w3-button w3-black">Переглянути</button>
  </form>

<!-- SEGMENTS TABLE -->
  <table id="segments" class="w3-table-all w3-container">
    <thead>
      <tr class="w3-black">
        <th>Номер у б/д</th>
        <th>Район</th>
      </tr>
    </thead>

    {% for segment in segment_list %}
    <tr>
      <td><a href="{% url 'main:segment_detail' street.id segment.id %}">{{ segment.id }}</a></td>
      <td>{{ segment.district }}</td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="5">Сегменти відсутні!</td>
    </tr>
    {% endfor %}
  </table>
</div>

<script src="{% static 'js/street_detail.js' %}"></script>

<!-- MAP SETUP -->
<script type="text/javascript">
  function map_init(map,options)
  {
    var lon = "{{ xcoord }}".replace(",", ".");
    var lat = "{{ ycoord }}".replace(",", ".");
    map.setView([lat, lon], 16);
    var myStyle = {
      "color": "#ff7800",
      "weight": 5,
      "opacity": 0.65
    };
    {% for s in segment_list.all %}
      var geojson = {{s.geom.geojson | safe}}
      L.geoJSON(geojson, {
        style: myStyle,
        onEachFeature: function (feature, layer) {
        layer.bindPopup('<h3> {{street}} '+"{{street.type}}"+'</h3>'+'<h4>Номер сегменту у БД: '+{{s.id}}+'</h4>'+'<h4>Район: '+"{{s.district}}"+'</h4>');
        }
        }).addTo(map);
    {% endfor %}
    map.fitBounds(geojson.getBounds());
  }
</script>

{% endblock %}

street/templates/main/import.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
{% endblock %}

street/templates/main/operations.html
{% extends 'base.html' %}


{% block content %}

{% load static %}


<div class="w3-content">

  <div class="w3-black w3-bar w3-center">
    <h2>Створити операцію на основі документу:</h2>
    <a target = "_blank" href = "/media/{{ document.path_pdf }}" class="w3-xlarge">{{ document.origin_name }} ({{ document.name }}) {{ document.date }}</a>
  </div>

    <br>

  <div class="w3-row-padding w3-center">
    <h4>Доступні операції:</h4>
    <div class="w3-quarter">
      <div class="w3-hover-shadow w3-panel w3-card w3-round-xlarge w3-light-green" style="width:70%; margin:auto"><a href="{% url 'main:street_new' %}">
        <p class="w3-large">Додати вулицю</p>
        <p><i class="fa fa-plus w3-xxlarge" aria-hidden="true"></i></p></a>
      </div>
    </div>
  </div>

</div>

{% endblock %}

street/templates/main/rename_street.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/add_document.css' %}">

<div class="w3-content">
    <div class="w3-black w3-bar w3-center">
      <h2>Змінити назву вулиці {{street.name}}:</h2>
      <p>На основі документу:</p>
      <a target = "_blank" href = "/media/{{ document.path_pdf }}" class="w3-xlarge">{{ document.origin_name }} ({{ document.name }}) {{ document.date }}</a>
    </div>
    <form method="POST" class="post-form" action="{% url 'main:street_rename' street.id %}">{% csrf_token %}
        <label for="street_name">Нова назва вулиці:</label>
        <input id = "street_name" type="text" name="street_name" placeholder="Введіть назву..">

        <label for="operation_date">Дата проведення операції:</label>
        <input id = "operation_date" type="date" name="operation_date" >
        <button type="submit" class="w3-button w3-black w3-right">Змінити</button>
    </form>
</div>
{% endblock %}

street/templates/main/segment_detail.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

{% load leaflet_tags %}
{% leaflet_css %}
{% leaflet_js %}
<head>

  <style>
          body {
              padding: 0;
              margin: 0;
          }
          html, body, #main {
              height: 100%;
              width: 100%;
          }
          #map {
            height: 100%;
          }
  </style>
</head>

<link rel="stylesheet" href="{% static 'css/street_list.css' %}">


<div class="sidebar w3-center">
  <h3 class="w3-padding">Панель модератора:</h3>

  <div class="w3-hover-shadow w3-panel w3-card w3-round-xlarge w3-light-green" style="width:70%; margin:auto"><a href="{% url 'main:segment_change_geom' street_id segment.id %}">
    <p>Змінити геометрію сегменту</p>
    <p><i class="fa fa-road w3-xxlarge" aria-hidden="true"></i></p></a>
  </div>
  <hr>
  <div class="w3-hover-shadow w3-panel w3-card w3-round-xlarge w3-light-green" style="width:70%; margin:auto"><a href="{% url 'main:segment_change_attributes' street_id segment.id %}">
    <p>Змінити атрибути сегменту</p>
    <p><i class="fa fa-edit w3-xxlarge" aria-hidden="true"></i></p></a>
  </div>
</div>

<body style = "height: 100%;width: 100%;padding: 0px; margin: 0px">

  <div class="w3-row">
    <div class="w3-col w3-center w3-container m3 l2 w3-light-grey">
      <!-- sidebar here -->
    </div>
    <div class="w3-col w3-container m9 l10">
    
      <div class="w3-black w3-center">
        <a href={% url 'main:detail' street_id %} class="w3-left w3-button w3-black">Повернутись назад</a>
        <h2>Сегмент: {{ segment.id }}</h2>
      </div>


      <div class="w3-row-padding">
        <div class="w3-half">
          <div style="height: 400px;" id="map">{% leaflet_map "main" callback="map_init" %}</div>
        </div>

        <div class="w3-half">
          <h2>Атрибути сегменту:</h2>
          <ul class="w3-ul">
            <li>Номер у БД: {{ segment.id }}</li>
            <li>Район: {{ segment.district }}</li>
          </ul>
        </div>
      </div>
    </div>  
  </div>

</body>

<head>
  <style>
          body {
              padding: 0;
              margin: 0;
          }
          html, body, #main {
              height: 100%;
              width: 100%;
          }
          #map {
            height: 100%;
          }
  </style>
</head>
<script type="text/javascript">
  function map_init(map,options){
    var lon = "{{ xcoord }}".replace(",", ".");
    var lat = "{{ ycoord }}".replace(",", ".");
    map.setView([lat, lon], 16);
    var myStyle = {
      "color": "#ff7800",
      "weight": 5,
      "opacity": 0.65
    };
      var geojson = {{segment.geom.geojson | safe}}
      L.geoJSON(geojson, {
        style: myStyle,
        onEachFeature: function (feature, layer) {
        layer.bindPopup('<h4>Номер сегменту у БД: '+{{segment.id}}+'</h4>'+'<h4>Район: '+"{{segment.district}}"+'</h4>');
        }
        }).addTo(map);
    map.fitBounds(geojson.getBounds());

  }
</script>
{% endblock %}

street/templates/main/street_chronology.html

{% extends 'base.html' %}

{% block content %}
{% load leaflet_tags %}
{% leaflet_css %}
{% leaflet_js %}
<head>
  <style>
          body {
              padding: 0;
              margin: 0;
          }
          html, body, #main {
              height: 100%;
              width: 100%;
          }
          #map {
            height: 100%;
          }
  </style>
</head>

<body >
    
    <div class="w3-row-padding w3-padding-large">
      <div class="w3-twothird">
        <div style="width: 100%;" class="w3-center">
          <form method="POST" class="post-form" action="{% url 'main:street_chronology' street_id %}">{% csrf_token %}
          <label for="#date">Переглянути хронологію на дату:</label>
          <input required id="date" name="date" type="date">
          <button type="submit" class="w3-button w3-black">Переглянути</button>
        </form>
        </div>
        <div style="height: 500px;" id="map">{% leaflet_map "main" callback="map_init" %}</div>
      </div>
      <div class="w3-third w3-container">
        <br>
        <br>
        <h2>Хронологічні дані:</h2>
        <p>Дата:{{ date }}</p>
        <h3>Вулиці та сегменти:</h3>
        <ul style="width: 300px;" class="w3-ul w3-card-4">
          {% for street,segments in hash_street.items %}
          {% if segments %}
          <li class="w3-large w3-khaki w3-round w3-text-black">
          {% else %}
          <li class="w3-large w3-text-grey">
          {% endif %}
            {{ street.type }}: <a href="{% url 'main:detail' street.id %}">{{ street.name }}</a>
            {% if segments %}
              <ul  class="w3-border-left w3-border-cyan">
                
                <span>Сегменти:</span>
                {% for s in segments %}
                  <li>{{ s.id }} -- {{ s.district }}</li>
                {% endfor %}
              </ul>
              {% endif %}
            </{{>
          
          {% endfor %}
          </ul>
      </div>
    </div>
 
</body>
<script type="text/javascript">
  function map_init(map,options)
  {
    map.setView([50.45, 30.5], 11);
    var myStyle = {
      "color": "#ff7800",
      "weight": 5,
      "opacity": 0.65
    };
    {% for street,segments in hash_street.items %}
      {% for s in segments %}
      var geojson = {{s.geom.geojson | safe}}
      L.geoJSON(geojson, {
        style: myStyle,
        onEachFeature: function (feature, layer) {
        layer.bindPopup('<p> {{street.name}} '+"{{street.type}}"+'</p>'+'<p>Номер сегменту у БД: '+{{s.id}}+'</p>'+'<p>Район: '+"{{s.district}}"+'</p>');
        }
        }).addTo(map);
        {% endfor %}
    {% endfor %}
    //map.fitBounds(geojson.getBounds());
  }
</script>
{% endblock %}